import Head from 'next/head'
import Feed from '../sections/Feed'
import Sidebar from '../sections/Sidebar'
import Widget from '../sections/Widget'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        <Sidebar/>
        <Feed/>
        <Widget/>
      </div>
    </div>
  )
}
